spring.application.name=flood-rescue-backend

server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=flood_rescue_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Sa@12345678
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
